markdown: kramdown

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables"]
  
include:
  - zsemlebot/index.md
  - zsemlebot/index2.md
  - README.md

theme: jekyll-theme-minimal
